name: Deploy
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "eh-krumynas-backend" #Must be unique in Heroku
          heroku_email: "evaldas.grublys@gmail.com"
          buildpack: "https://github.com/jincod/dotnetcore-buildpack"
  build-web-app:
    name: React App Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "eh-krumynas-frontend"
          heroku_email: "evaldas.grublys@gmail.com"